;;;; One generic dispatcher for demo.toml commands the product CLI cannot
;;;; express: boot, resume, corporate. Ask/research/improve/ingest go
;;;; through `demiurge demo` (loaded after this file only when needed).
;;;;
;;;;   sbcl --load demos/prelude.lisp --load demos/runner.lisp -- demos/s2-boot

(in-package #:demiurge-parity)

(defun demo-narrate (fmt &rest args)
  (format t "~&~%── ~?~%" fmt args)
  (finish-output))

(defun demo-look-at (fmt &rest args)
  (format t "~&   look at: ~?~%" fmt args)
  (finish-output))

(defun demo-kv (key value)
  (format t "~&   ~A: ~S~%" key value)
  (finish-output))

(defun %runner-dir ()
  (let ((arg (or (first (uiop:command-line-arguments))
                 (error "runner requires a demo directory"))))
    (uiop:ensure-directory-pathname arg)))

(defun %peek-command (dir)
  (let ((demo (merge-pathnames "demo.toml" dir)))
    (unless (probe-file demo)
      (return-from %peek-command :boot))
    (loop for raw in (uiop:read-file-lines demo)
          for line = (string-trim '(#\Space #\Tab) raw)
          when (and (>= (length line) 8)
                    (string-equal "command" line :end2 7)
                    (find #\= line))
            do (let* ((eqpos (position #\= line))
                      (val (string-trim '(#\Space #\Tab #\")
                                        (subseq line (1+ eqpos)))))
                 (return (intern (string-upcase val) :keyword)))
          finally (return :boot))))

(defun %config-path (dir)
  (or (probe-file (merge-pathnames "corporate.toml" dir))
      (probe-file (merge-pathnames "expert.toml" dir))))

(defun run-boot-demo (dir)
  (declare (ignore dir))
  (demo-narrate "S2 boot — personal profile factory in a clean temp dir")
  (demo-look-at "profile-kind, bound journal/session/chunker/rag/llm stores, SQLite paths under data-dir")
  (with-tmp-dir (tmp)
    (demo-narrate "Calling BOOT-PERSONAL-PROFILE with data-dir ~A" tmp)
    (let* ((profile (boot-personal-profile :data-dir tmp))
           (paths (profile-sqlite-paths profile)))
      (demo-kv "personal-profile-p" (demiurge:personal-profile-p profile))
      (demo-kv "profile-kind" (demiurge:profile-kind profile))
      (demo-kv "journal bound" (and (demiurge:profile-journal profile) t))
      (demo-kv "session-store bound" (and (demiurge:profile-session-store profile) t))
      (demo-kv "chunker bound" (and (demiurge:profile-chunker profile) t))
      (demo-kv "rag-store bound" (and (demiurge:profile-rag-store profile) t))
      (demo-kv "llm-catalog bound" (and (demiurge:profile-llm-catalog profile) t))
      (demo-kv "data-dir exists" (and (probe-file (uiop:ensure-directory-pathname tmp)) t))
      (demo-narrate "Expected SQLite files under the temp data-dir")
      (demo-look-at "journal.sqlite / sessions.sqlite may be absent when the backend is in-memory")
      (dolist (key '(:journal :sessions :rag))
        (let ((path (getf paths key)))
          (demo-kv (format nil "~A path" key) (namestring path))
          (demo-kv (format nil "~A exists" key) (and (probe-file path) t))))
      (demo-narrate "S2 done. Reviewer: :PERSONAL kind and stores bound from a clean temp dir."))))

(defun run-resume-demo (dir)
  (declare (ignore dir))
  (demo-narrate "S7 durability — 2-step journal, child SBCL kill, parent replay")
  (demo-look-at "journal replay counts: before-count, after-count, fresh-1/fresh-2, side-effect counts")
  #-sbcl
  (progn
    (demo-narrate "This demo requires SBCL (sb-ext:exit :abort t). Stopping.")
    (uiop:quit 1))
  (unless (system-available-p "sql-backend-sqlite3")
    (demo-narrate "sql-backend-sqlite3 is not loadable. Stopping.")
    (uiop:quit 1))
  (demo-narrate "Launching a child SBCL that journals step-1, writes a side-effect, then aborts")
  (demo-look-at "shared SQLite journal: one STEP-COMPLETED before resume")
  (let ((result (run-kill-resume :task-id "demo-resume")))
    (demo-narrate "Parent replayed the journal and continued with step-2")
    (demo-kv "before-count (steps before resume; expect 1)" (getf result :before-count))
    (demo-kv "after-count (steps after resume; expect 2)" (getf result :after-count))
    (demo-kv "step-names (expect step-1 step-2)" (getf result :step-names))
    (demo-kv "fresh-1 (step-1 body re-executed? expect 0)" (getf result :fresh-1))
    (demo-kv "fresh-2 (step-2 ran on resume? expect 1)" (getf result :fresh-2))
    (demo-kv "effect-1 (side-effect written exactly once)" (getf result :effect-1))
    (demo-kv "effect-2 (side-effect written on resume)" (getf result :effect-2))
    (demo-narrate "Replay contract: step-1 came from the journal (fresh-1=0); step-2 executed once.")
    (demo-narrate "S7 done. Reviewer: before-count=1, after-count=2, fresh-1=0, fresh-2=1, effects=1/1.")))

(defun run-corporate-demo (dir)
  (dolist (name '("demiurge/serve" "demiurge/observe"))
    (unless (asdf:find-system name nil)
      (format *error-output* "~&DEMO FAIL: ~A is not findable~%" name)
      (uiop:quit 1))
    (asdf:load-system name))
  (demo-narrate "Corporate boot — make-corporate-profile with memory/sqlite fallback")
  (demo-look-at "kind, tenant, tenant-scoped ids; Clack /healthz /readyz 200; unauthenticated / → 302")
  (let ((cfg-path (or (%config-path dir)
                      (error "corporate demo needs corporate.toml or expert.toml"))))
    (with-tmp-dir (tmp)
      (let* ((cfg (demiurge:load-demiurge-config :path cfg-path :env nil))
             (profile (demiurge:make-corporate-profile
                       :data-dir tmp
                       :config cfg
                       :tenant "acme"
                       :force-recording t
                       :journal (task:make-in-memory-journal)
                       :session-store (conversation-protocol:make-in-memory-conversation-store)
                       :rag-store (rag-backend-memory:make-memory-vector-store)
                       :chunker (rag-backend-text:make-recursive-character-chunker
                                 :size 200 :overlap 20)
                       :llm-catalog (make-scripted-llm-catalog)
                       :default-model "mock")))
        (demo-narrate "Factory returned a corporate profile (no live Postgres)")
        (demo-kv "corporate-profile-p" (demiurge:corporate-profile-p profile))
        (demo-kv "profile-kind" (demiurge:profile-kind profile))
        (demo-kv "tenant" (demiurge:profile-tenant profile))
        (demo-look-at ":CORPORATE kind and tenant \"acme\" — memory journal/session/rag, not a DSN")
        (demiurge:with-tenant (demiurge:profile-tenant profile)
          (demo-narrate "Tenant-scoped identifiers")
          (demo-kv "tenant-task-id echo" (demiurge:tenant-task-id "echo"))
          (demo-kv "tenant-corpus-name docs" (demiurge:tenant-corpus-name "docs"))
          (demo-kv "current-tenant" (demiurge:current-tenant)))
        (let* ((domain (demiurge:make-echo-expert
                        :backend (make-scripted-llm)
                        :name "demo-corporate-echo"
                        :profile profile))
               (app (demiurge/serve:make-expert-app domain profile))
               (hz (funcall app '(:request-method :get :path-info "/healthz")))
               (rz (funcall app '(:request-method :get :path-info "/readyz")))
               (root (funcall app '(:request-method :get :path-info "/"))))
          (demo-narrate "make-expert-app Clack env (no session cookie)")
          (demo-kv "GET /healthz status" (first hz))
          (demo-kv "GET /readyz status" (first rz))
          (demo-kv "GET / status" (first root))
          (demo-kv "GET / Location" (getf (second root) :location))
          (demo-look-at "/healthz and /readyz stay unauthenticated (C4). GET / is a 302 to /login.")
          (demo-narrate "Corporate-boot done. Reviewer: kind/tenant scoped; probes 200; / challenges."))))))

(defun dispatch-demo (dir)
  (let ((cmd (%peek-command dir)))
    (demo-narrate "generic runner command=~a dir=~a" cmd dir)
    (ecase cmd
      (:boot (run-boot-demo dir))
      (:resume (run-resume-demo dir))
      (:corporate (run-corporate-demo dir))
      ((:ask :research :improve :ingest)
       (error "command ~a must go through demiurge demo, not the parity runner" cmd)))))

(dispatch-demo (%runner-dir))
(uiop:quit 0)
